# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
# Work around https://github.com/r-lib/roxygen2/issues/1121
warnings_are_errors: false

r:
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'
